name: "LEAP Catalog Action"
description: "Install package, validate feedstocks, and generate catalog"
author: "LEAP"
inputs:
  version:
    description: "Version of the package to install"
    required: false
    default: "0.0.8"
  validation-path:
    description: "Path to the feedstocks input YAML file for validation"
    required: false
  single-feedstock:
    description: "Path to a single feedstock YAML file to validate"
    required: false
  generation-path:
    description: "Path to the feedstocks input YAML file for generation"
    required: false
  output-directory:
    description: "Path to the output directory for the generated catalog"
    required: false
outputs: {}
runs:
  using: "composite"
  steps:
    - run: |
        ${{github.action_path}}/leap-catalog/run.sh "${{ inputs.version }}" "${{ inputs.validation-path }}" "${{ inputs.single-feedstock }}" "${{ inputs.generation-path }}" "${{ inputs.output-directory }}"
      shell: bash
