name: Test LEAP Catalog Action

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: validate single
        uses: ./leap-catalog
        with:
          version: "0.0.12"
          single-feedstock: "https://raw.githubusercontent.com/leap-stc/LEAP_template_feedstock/main/feedstock/catalog.yaml"

      - name: validate many
        uses: ./leap-catalog
        with:
          validation-path: "https://raw.githubusercontent.com/leap-stc/data-management/main/catalog/input.yaml"

      - name: Validate and Generate catalog
        uses: ./leap-catalog
        with:
          generation-path: "https://raw.githubusercontent.com/leap-stc/data-management/main/catalog/input.yaml"
          output-directory: "catalog/"
