name: Test LEAP Catalog Action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: validate single
        uses: ./leap-catalog
        with:
          version: "0.0.16"
          single-feedstock: "https://github.com/carbonplan/ocean-carbon-sink-data-feedstock/blob/main/feedstock/catalog.yaml"

      - name: Validate and Generate catalog for single feedstock
        uses: ./leap-catalog
        with:
          generation-single: "https://github.com/carbonplan/ocean-carbon-sink-data-feedstock/blob/main/feedstock/catalog.yaml"
          output-directory: "catalog/"

      - name: validate many
        uses: ./leap-catalog
        with:
          validation-path: "https://raw.githubusercontent.com/leap-stc/data-management/main/catalog/input.yaml"

      - name: Validate and Generate catalog
        uses: ./leap-catalog
        with:
          generation-path: "https://raw.githubusercontent.com/leap-stc/data-management/main/catalog/input.yaml"
          output-directory: "catalog/"
